# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=250)),
                ('rank', models.CharField(max_length=3)),
                ('provider_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('service_charges', models.CharField(max_length=50)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Cloud')),
            ],
        ),
    ]
